# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :odoo do |odoo|
    odoo.vm.box = "ubuntu/trusty64"
    odoo.vm.provision :shell, path: "setup_odoo.sh"
    odoo.vm.synced_folder "D:/SharedFolder/", "/home/vagrant/SharedFolder"

    # Allow insecure box fetching
    odoo.vm.box_download_insecure = true

    odoo.vm.network "private_network", ip: "192.168.50.4"
    odoo.vm.hostname = "odoo"
  end

  config.vm.define :snapshot do |snapshot|
    snapshot.vm.box = "ubuntu/trusty64"
    # By default global project folder is shared in vagrant under /vagrant directory
    #snapshot.vm.synced_folder "shared/", "/home/vagrant/shared"
    # Allow insecure box fetching
    snapshot.vm.hostname = "snapshot"
    snapshot.vm.box_download_insecure = true

    snapshot.vm.provision :shell, path: "setup_rsnapshot.sh"
    snapshot.vm.provision "shell", run: "always", inline: "cp shared/rsnapshot.conf /etc/"
  end

  # To specify where vagrant will download the box, set VAGRANT_HOME in env
  # Then set VBox's default machine folder to match VAGRANT_HOME

  # To run vagrant with more info diplayed set VAGRANT_LOG=info

  # C:\Users\Micha?l Yadaba\VirtualBox VMs
 
end
